version: "3"


services:
  postgres:
    image: postgres:14.4-alpine
    container_name: "azbykamebeli_postgres"
    restart: on-failure
    # make it available from localhost
    # or use "expose: - 5432" for in-container access only
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "admin"
      POSTGRES_DB: "azbykamebeli"
    volumes:
      # connect db to volume not to lose data after stop
      - postgres-data:/var/lib/postgresql/data
      # populate db with data (pg_dump.sql)
      - .:/docker-entrypoint-initdb.d

  app:
    build: .
    container_name: "azbykamebeli_app"
    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]
    restart: on-failure
    ports:
      - "8000:8000"
    environment:
      # connect to postgres container
      DATABASE_URL: "postgresql+asyncpg://postgres:admin@postgres:5432/azbykamebeli"
    depends_on:
      - postgres

volumes:
  postgres-data:
