"""Init

Revision ID: f276fd8dfc24
Revises: 
Create Date: 2022-07-05 11:52:11.929169

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f276fd8dfc24'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('straight_sofas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sku', sa.Integer(), nullable=True),
    sa.Column('item_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=100), nullable=True),
    sa.Column('full_price', sa.Integer(), nullable=True),
    sa.Column('sale_price', sa.Integer(), nullable=True),
    sa.Column('availability', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_straight_sofas_sku'), 'straight_sofas', ['sku'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_straight_sofas_sku'), table_name='straight_sofas')
    op.drop_table('straight_sofas')
    # ### end Alembic commands ###
